### ISSUE TITLE
Proper descriptions / cleanup?

### ISSUE THREAD

**Issue by subworx** [bad1dea/NXCheats#16]
Hi, 
first thank you so much for maintaining this, much appreciated.

My question though: could you please clean up the (Yuzu) cheats and possibly add better descriptions? 

I don't understand why there's Jump codes with #7, 8, 9 and 10 - and what they do or how they differ, if at all. I found #7 to support 1.0.0 and 1.1.0 while 8, 9 and 10 only cover one version each.

Also, why are the Item multiplier cheats spread accross #6, 7, 8 and 9, and why is one version marked with a star?

Thank you :)

**Comment by ZeroCool940711** [comment]
I was wondering the same things, I pretty much just went and looked at the modified date on the folders and used the most recent modified one because I had no idea what each folder was for or how they are different.

**Comment by bad1dea** [comment]
Hi, the emulator support is just because I can do it -- I don't support it though, it's generated off of the Switch version of the cheats.

There are multiple versions of said cheats because they do the "same" thing with just a different multiplier, i.e one does 2 times, 4 times, 10 times, etc etc -- to give player different options instead of saying, hey can you make it do 10x instead of 2x.

The star beside the cheat is "preferred/suggested" as in that's the option I would suggest using, as in that's what I would use.
