### ISSUE TITLE
"Inf. Equipment Durability (Fire will still break it.)" - No Longer Functioning In Yuzu EA Build

### ISSUE THREAD

**Issue by InfiniteParallel** [bad1dea/NXCheats#85]
Yuzu EA 3612, TOTK 1.1.1, no other cheats loaded, all mods are strictly graphical and loading as IPSwitch, no LayeredFS mods.

The failure of this cheat started with the most current build of Yuzu EA as of the creation of this issue, Yuzu EA 3612. I have the cheat loaded correctly, and it is showing as loaded properly according to Yuzu, but my equipment is still losing durability as it is used.

I ran this cheat in 1.1.0, updated for 1.1.1 and have never had any issues with it. Before installing EA 3612 it was running perfectly with Yuzu EA 3607. Somehow something has changed with EA 3612 that is causing this cheat to fail.

Let me know if you need any particular logs, files, etc... I'll be willing to provide whatever is needed. Without this cheat the only alternative is a LayeredFS mod that dramatically slows loading times.

**Comment by bad1dea** [comment]
Sorry mate, hard to support emulators because they change things so often. Try updating to 1.1.2 and try.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: InfiniteParallel ***@***.***>
Sent: Thursday, May 25, 2023 11:57:20 PM
To: bad1dea/NXCheats ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [bad1dea/NXCheats] "Inf. Equipment Durability (Fire will still break it.)" - No Longer Functioning In Yuzu EA Build (Issue #85)


Yuzu EA 3612, TOTK 1.1.1, no other cheats loaded, all mods are strictly graphical and loading as IPSwitch, no LayeredFS mods.

The failure of this cheat started with the most current build of Yuzu EA as of the creation of this issue, Yuzu EA 3612. I have the cheat loaded correctly, and it is showing as loaded properly according to Yuzu, but my equipment is still losing durability as it is used.

I ran this cheat in 1.1.0, updated for 1.1.1 and have never had any issues with it. Before installing EA 3612 it was running perfectly with Yuzu EA 3607. Somehow something has changed with EA 3612 that is causing this cheat to fail.

Let me know if you need any particular logs, files, etc... I'll be willing to provide whatever is needed. Without this cheat the only alternative is a LayeredFS mod that dramatically slows loading times.
